import { writeFile } from "fs/promises";
import type { Tile } from "./types.js";
import { countTiles } from "./util.js";

const hands: Tile[][] = [
	[
		{ color: "red", shape: "circle" },
		{ color: "orange", shape: "circle" },
		{ color: "orange", shape: "star" },
		{ color: "yellow", shape: "clover" },
		{ color: "purple", shape: "triangle" },
		{ color: "purple", shape: "triangle" },
	],
	[
		{ color: "orange", shape: "star" },
		{ color: "yellow", shape: "square" },
		{ color: "green", shape: "clover" },
		{ color: "green", shape: "clover" },
		{ color: "blue", shape: "circle" },
		{ color: "blue", shape: "triangle" },
	],
	[
		{ color: "yellow", shape: "diamond" },
		{ color: "yellow", shape: "star" },
		{ color: "green", shape: "star" },
		{ color: "purple", shape: "circle" },
		{ color: "purple", shape: "square" },
		{ color: "purple", shape: "star" },
	],
	[
		{ color: "red", shape: "clover" },
		{ color: "orange", shape: "clover" },
		{ color: "blue", shape: "clover" },
		{ color: "blue", shape: "square" },
		{ color: "blue", shape: "square" },
		{ color: "purple", shape: "diamond" },
	],
	[
		{ color: "red", shape: "square" },
		{ color: "red", shape: "star" },
		{ color: "orange", shape: "triangle" },
		{ color: "green", shape: "diamond" },
		{ color: "blue", shape: "diamond" },
		{ color: "purple", shape: "clover" },
	],
	[
		{ color: "red", shape: "clover" },
		{ color: "red", shape: "square" },
		{ color: "green", shape: "diamond" },
		{ color: "purple", shape: "circle" },
		{ color: "purple", shape: "circle" },
		{ color: "purple", shape: "square" },
	],
	[
		{ color: "orange", shape: "square" },
		{ color: "orange", shape: "star" },
		{ color: "yellow", shape: "triangle" },
		{ color: "yellow", shape: "triangle" },
		{ color: "green", shape: "circle" },
		{ color: "green", shape: "clover" },
	],
	[
		{ color: "red", shape: "circle" },
		{ color: "red", shape: "diamond" },
		{ color: "red", shape: "star" },
		{ color: "yellow", shape: "circle" },
		{ color: "blue", shape: "star" },
		{ color: "blue", shape: "triangle" },
	],
	[
		{ color: "red", shape: "circle" },
		{ color: "red", shape: "square" },
		{ color: "red", shape: "triangle" },
		{ color: "orange", shape: "diamond" },
		{ color: "orange", shape: "diamond" },
		{ color: "purple", shape: "star" },
	],
	[
		{ color: "red", shape: "clover" },
		{ color: "yellow", shape: "circle" },
		{ color: "yellow", shape: "diamond" },
		{ color: "green", shape: "square" },
		{ color: "purple", shape: "clover" },
		{ color: "purple", shape: "square" },
	],
	[
		{ color: "red", shape: "diamond" },
		{ color: "red", shape: "triangle" },
		{ color: "orange", shape: "clover" },
		{ color: "blue", shape: "diamond" },
		{ color: "blue", shape: "star" },
		{ color: "purple", shape: "diamond" },
	],
	[
		{ color: "orange", shape: "circle" },
		{ color: "yellow", shape: "clover" },
		{ color: "yellow", shape: "clover" },
		{ color: "green", shape: "triangle" },
		{ color: "blue", shape: "circle" },
		{ color: "blue", shape: "clover" },
	],
	[
		{ color: "orange", shape: "diamond" },
		{ color: "orange", shape: "square" },
		{ color: "yellow", shape: "triangle" },
		{ color: "green", shape: "circle" },
		{ color: "green", shape: "diamond" },
		{ color: "blue", shape: "diamond" },
	],
	[
		{ color: "orange", shape: "clover" },
		{ color: "yellow", shape: "square" },
		{ color: "yellow", shape: "star" },
		{ color: "green", shape: "circle" },
		{ color: "green", shape: "square" },
		{ color: "purple", shape: "clover" },
	],
	[
		{ color: "orange", shape: "circle" },
		{ color: "orange", shape: "triangle" },
		{ color: "yellow", shape: "circle" },
		{ color: "yellow", shape: "diamond" },
		{ color: "green", shape: "star" },
		{ color: "green", shape: "triangle" },
	],
	[
		{ color: "red", shape: "triangle" },
		{ color: "yellow", shape: "star" },
		{ color: "blue", shape: "clover" },
		{ color: "blue", shape: "square" },
		{ color: "blue", shape: "triangle" },
		{ color: "purple", shape: "star" },
	],
	[
		{ color: "red", shape: "star" },
		{ color: "yellow", shape: "square" },
		{ color: "green", shape: "star" },
		{ color: "blue", shape: "circle" },
		{ color: "blue", shape: "star" },
		{ color: "purple", shape: "triangle" },
	],
	[
		{ color: "red", shape: "diamond" },
		{ color: "orange", shape: "square" },
		{ color: "orange", shape: "triangle" },
		{ color: "green", shape: "square" },
		{ color: "green", shape: "triangle" },
		{ color: "purple", shape: "diamond" },
	],
];

writeFile("./hands.json", JSON.stringify(hands.map((hand) => [countTiles(hand), hand])));
